### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by dmora219**

### CODE REVIEW

**Review by gavand-sagar — DISMISSED** [review]
Make hi --> Hi

**Review by ghost — APPROVED** [review]

**Review by VLKH3 — APPROVED** [review]

**Review by prisimstudent — APPROVED** [review]

**Review by PrismStudent07 — APPROVED** [review]

**Comment by gavand-sagar** [comment]
> Make hi --> Hi

**Comment by dmora219** [comment]
> Make hi --> Hi

I hate you

**Review by Marcombuyu98 — COMMENTED** [review]
hi

**Review by gavand-sagar — CHANGES_REQUESTED** [review]
NO, please make it capital.

**Review by gavand-sagar — APPROVED** [review]

**Pull request closed without merging**
